### ISSUE TITLE
[Suggestion] Alternative distribution as a dotnet cli tool?

### ISSUE THREAD

**Issue by NinoFloris** [datalust/piggy#11]
Would be great if you could install and use piggy as a DotNetCliToolReference.

:) Looking good otherwise, going to test run this with our proj soon!

**Comment by nblumhardt** [comment]
Thanks for the suggestion! As you guess, I haven't got any experience with shipping .NET CLI tools, but it'd be interesting to explore :-)

**Comment by nblumhardt** [comment]
Resolved in #35 🎉 .. seven years later! 😆 

Hope all's well with you @NinoFloris 👋
