### ISSUE TITLE
Rollback support?

### ISSUE THREAD

**Issue by rattrayalex** [datalust/piggy#19]
A quick glance through the docs doesn't mention rollbacks. Does piggy have support for a `rollback` command and associated "down" sql to specify rollback behavior (eg; as in https://github.com/thuss/standalone-migrations)?

**Comment by nblumhardt** [comment]
Hi @rattrayalex - thanks for getting in touch.

No, Piggy's designed as a roll-forward-only system. I don't think this will suit everyone, but after years of using DbUp I'm convinced that roll-forward-only is the way to go, so there are no current plans to introduce rollback.

**Comment by rattrayalex** [comment]
Got it! Might be worth sharing your philosophy in the readme, people might find it interesting. Thanks!

**Comment by nblumhardt** [comment]
Thanks, will try to do that at some point :-) .. I think there's a good write-up out there somewhere by Paul Stovell, who originally wrote DbUp - will link it if I can find it :+1:
