### ISSUE TITLE
NUPKG includes extraneous files

### ISSUE THREAD

**Issue by nblumhardt** [datalust/piggy#23]
I just noticed that after installing the new _Datalust.Piggy_ package, some unexpected content is linked into my CSPROJ:

![image](https://user-images.githubusercontent.com/342712/60940732-dedf4a80-a31f-11e9-8ea0-050e9a1b57a0.png)

(We get the Piggy icon and Attribution folder.)

Guessing this is a side-effect of publishing the project as an executable before packaging it as a library :-)

**Comment by todthomson** [comment]
Closing, as this isn't the case anymore.
